usort/config.py
usort/sorting.py
usort/tests/functional.py
usort/tests/sort_key.py

This changes `Config.known` to a mapping of casefolded package names to
categories, which allows both case insensitive sorting and the ability
to treat "cProfile" as a part of stdlib. This would also allow, eg,
configuration that specifies "ipython" even though the import is
"IPython".
Fixes #26

Makes known modules/categories case insensitive

---

CHANGELOG.md
docs/guide.rst
usort/config.py
usort/sorting.py
usort/tests/config.py
usort/tests/functional.py
usort/tests/sort_key.py

When determining if imports are sortable, this adds some normalization,
and checks each part of the import name against the configured list
of known imports with side effects. If the full import, or any of the
combined stem parts, are in the configured list, then the import is
considered as unsortable, effectively creating an implicit barrier the
same way that `usort:skip` directives would.

Add configurable set of imports with side effects

---

CHANGELOG.md
Makefile
docs/guide.rst
usort/config.py
usort/tests/config.py

Fixes #40: This option name was inconsistent with the use of "category",
so change the name to `default_category` to make it consistent.

Rename `default_section` to `default_category`

---

usort/config.py
usort/tests/config.py

This isn't used anywhere from CLI; drop it for now and focus on using
pyproject.toml for configuration.

Remove unused `update_from_flags` function

---

usort/cli.py
usort/sorting.py
usort/tests/cli.py
usort/util.py

Rather than printing a raw exception with duplicate filename info, this just prints the exception message directly, and updates the exception message to be more explicit and detailed about the error that occurred. When parsing fails on all versions, we pick the parsing error from the newest syntax version and print the filename, line number, syntax version, piece of offending code, and the parsing error from LibCST:
```shell-session
(.venv) jreese@garbodor ~/workspace/usort parse-error± » cat foo.py
while i := foo():
print("i"
(.venv) jreese@garbodor ~/workspace/usort parse-error± » usort format foo.py
Error sorting foo.py: Syntax Error @ 3:1.
Incomplete input. Encountered a dedent, but expected ')'.
print("i"
^
```
Fixes #44

Better parsing error messages

---

.github/workflows/build.yml
LICENSE

This will also include a push of the skel branch, which is generated by the templates in https://github.com/thatch/fb-skel (that one's upstream is https://github.com/python-packaging/skel, but with the license portion changed)

Run CI on py3.9

---

Makefile
requirements-dev.txt

We don't reflow yet, but this is safe enough and may help discover issues like #49 a bit earlier.

Use development usort to format ourselves

---

usort/config.py
usort/tests/cli.py
usort/tests/config.py

Need to be careful to not use Path.resolve() here which would follow the
symlink too early.
Fixes #43

Find configs outside of a given relative path.

---

usort/cli.py
usort/sorting.py
usort/tests/cli.py

Still diff str objects, because that's what moreorless supports today.
Fixes #46

Handle encoding properly, by delegating that to LibCST.

---

requirements.txt
setup.cfg
usort/config.py
usort/stdlibs.py
usort/tests/__init__.py
usort/tests/stdlibs.py

This should be a longer-term more reliable source of what top-level names come from stdlib.  It includes many more names (mostly C extensions) that were missing before; see https://github.com/jreese/stdlibs/pull/1 for some comparisons vs other possible sources.
While we're at it, take a stance on `__main__` being first-party code.  This seems to be most commonly used for subcommands in click, or for logging, but seems fragile and untestable to me.

Switch source of truth for stdlibs

---

Makefile
requirements-dev.txt

This will use the current checkout of usort for sorting if you use the
regular `make setup` target; if you set up your environment some other
way you'll need to use some care that it doesn't pull in just the public
deps of `ufmt`.

Switch code formatting to ufmt

---

usort/sorting.py
usort/tests/__init__.py
usort/tests/functional.py
usort/tests/sort_key.py
usort/tests/translate.py
usort/tests/util.py
usort/translate.py
usort/types.py
usort/util.py

* Adds `util.parse_import()` helper to parse statement and enforce type, with tests!
* Create a new `usort.translate` module.
* Move `types.SortableImport.from_node()` to `translate.import_from_node()`
* Rename `tests.sort_key` -> `tests.translate` to cover `import_from_node()`

Refactor from_node into separate translate module

---

.github/workflows/build.yml
Makefile

Type checks are closer to tests than lints, so include them in `make test`. Linting works on Python 3.9 now, so let's actually lint on that runtime too.

Move type checks to "test" phase, lint on Py 3.9

---

.github/dependabot.yml

Enables weekly updates (every Tuesdays) of dependencies from dependabot. This will generate a PR for each dependency being updated, and automatically handles creating, rebasing, landing, and deleting branches. PR's can be closed to skip individual versions, and comments can be used to tell dependabot to do things like skipping future minor/major versions, landing when CI is green, etc.

Enable dependabot for weekly dep updates

---

requirements.txt
setup.cfg
usort/__init__.py
usort/api.py
usort/cli.py
usort/tests/cli.py
usort/types.py
usort/util.py

- Uses `trailrunner.walk()` to find paths to sort.
- Adds `usort_file()` function to sort a single file.
- Use `trailrunner.run()` in `usort_path()` to use child process for
each file being sorted.
- Modify existing benchmark/timing APIs and usage to account for
multiprocessing usage and return timings in the `Result` object.
- Update `cli` to use new timings API for printing benchmarks
Fixes #61

Use trailrunner for walk and multiprocessing

---

CHANGELOG.md
README.md
docs/_static/custom.css
docs/api.rst
docs/conf.py
docs/guide.rst
docs/index.rst
usort/__init__.py
usort/api.py

Preview docs: https://usort--91.org.readthedocs.build/en/91/

Document public API, improve merging docs

---

docs/guide.rst
usort/sorting.py
usort/tests/functional.py

* Allow `#usort:skip` on the first line of multi-line imports
* Support `#usort:skip` after other comments/directives
* Document supported directive locations/positions
* Add test cases that fail on main but pass with PR
* Better error reporting from functional tests when exceptions occur during sorting
Fixes #27 
Docs preview: https://usort--108.org.readthedocs.build/en/108/guide.html#comments

Improved skip directive support

---

docs/guide.rst

We use `tool.black.line-length` from `pyroject.toml` when deciding if imports should be expanded to multiline or not. This mentions that in the configuration section.
Docs preview: https://usort--109.org.readthedocs.build/en/109/guide.html#tool-black

Document use of black line-length config

---

usort/config.py
usort/tests/config.py

Previous behavior was trying to read from `[black]` rather than `[tool.black]`.
Tested on pytorch-vision: https://gist.github.com/jreese/26a3b659c2fd9dbc7263539f497af878
Issue #107

Fix reading black line length from pyproject.toml

---

docs/conf.py
docs/guide.rst
usort/api.py
usort/config.py
usort/tests/config.py
usort/tests/functional.py

Supports reading a list of gitignore patterns from
`tool.usort.excludes`, and passes those values to trailrunner when
walking paths in `usort_path()`.
Includes tests and documentation updates to match.
Fixes #62 
Docs preview: https://usort--111.org.readthedocs.build/en/111/guide.html#excludes

Add new `excludes` configuration option

---

usort/sorting.py

Tracks indentation from indented nodes while walking the tree, rather than using `PositionProvider` metadata. For warnings about implicit block splitting and shadowed imports, defers resolving the metadata until after sorting is finished, and only if warnings were generated.
Overall, running `usort --benchmark diff <path/to/libcst/libcst>` shows approximately 20-30% performance improvement:
From main:
```
(.venv) jreese@butterfree ~/workspace/usort main  » usort --benchmark diff $workspace/libcst/libcst | grep total
total for /Users/jreese/workspace/libcst/libcst:   10497973 µs
```
With PR:
```
(.venv) jreese@butterfree ~/workspace/usort no-position-metadata  » usort --benchmark diff $workspace/libcst/libcst | grep total
total for /Users/jreese/workspace/libcst/libcst:   7079384 µs
```

Remove or defer use of PositionProvider metadata when sorting

---

usort/tests/functional.py
usort/translate.py

Adds a functional test covering broken behavior in 1.0, with a fix for that behavior.

Fix #128: handle single line from-imports with parens

---

README.md
docs/guide.rst
docs/index.rst
docs/why.rst

Adds new page to docs site, "Why µsort":
Preview docs: https://usort--130.org.readthedocs.build/en/130/
Closes #116

Add "why µsort" page to docs, update readme

---

usort/sorting.py
usort/tests/functional.py
usort/types.py

Fixes #145 when sorting basic imports with multiple items from
different categories.

Recalculate sort_key after sorting import items

---

docs/guide.rst
usort/sorting.py
usort/tests/functional.py

Before sorting and merging imports within a block, this looks for basic
(non-from) imports with more than one imported name, and then splits
that import into a separate import for each name. Comments are
duplicated from the original import to all split imports.
Fixes #140
Docs preview: https://usort--141.org.readthedocs.build/en/141/

Split basic import statements with multiple imported names

---

usort/api.py
usort/tests/cli.py

See #159
This optimises for a common use case when only one file is provided.
This change might belong to `trailrunner` repo as well.

Don't use trailrunner to format exactly one file

---

usort/api.py
usort/cli.py
usort/tests/cli.py

Previously, when passing multiple paths to the usort CLI, it would
call `usort_path()` separately for each path given, preventing any
chance of parallel processing. This means `usort check usort/**/*.py`
would take ~10X longer than `usort check usort`, and also results in
double formatting if a path appeared or was a child of multiple
arguments:
```
(.venv) jreese@butterfree ~/workspace/usort main  » time usort check usort
usort check usort  3.64s user 0.32s system 338% cpu 1.169 total
(.venv) jreese@butterfree ~/workspace/usort main  » time usort check usort usort usort
usort check usort usort usort  10.67s user 0.89s system 470% cpu 2.458 total
(.venv) jreese@butterfree ~/workspace/usort main  » time usort check usort/**/*.py usort/**/*.py usort/**/*.py
usort check usort/**/*.py …
```

Optimize passing multiple paths to usort CLI

---

usort/sorting.py

This is safe to do, because `module` always comes from the parser, so there are no duplicate nodes in the tree.
Here's a rough benchmark showing the benefits (`usort-skipcopy` has both the native libcst parser and this PR turned on):
|Snippet Code|Snippet Name|Runs|Mean|Median|Min|Max|Standard Deviation|
|---|---|---|---|---|---|---|---|
|usort.api.usort(src, usort_conf)|usort-default|20|143.9 ms|143.8 ms|142.67 ms|145.18 ms|927.37 µs|
|os.environ["LIBCST_PARSER_TYPE"] = "native"; usort.api.usort(src, usort_conf)|usort-native|28|106.09 ms|106.06 ms|105.68 ms|106.73 ms|282.61 µs|
|os.environ["USORT_SKIP_COPY"] = "true"; usort.api.usort(src, usort_conf)|usort-skipcopy|35|76.36 ms|76.15 ms|75.61 ms|77.52 ms|679.27 µs|
produced with
```
python -m fastero -s "import os, sys,usort; usort_conf = …
```

Skip deep copying CST after parsing

---

usort/sorting.py

This should prevent a large class of `RecursionError`s popping up for deeply nested syntax trees. On top of that, it makes usort ~37% faster even on smallish files like `sorting.py`.
```
usort-default: usort.api.usort(src, usort_conf)
Time  (mean ± σ):       100.57 ms ±   4.18 ms
Range (min  … max):      96.31 ms … 125.62 ms    [runs: 100]
usort-optimized: usort.api.usort(src, usort_opt)
Time  (mean ± σ):       73.59 ms ±  2.57 ms
Range (min  … max):     70.97 ms … 79.81 ms    [runs: 100]
Summary:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Bar Chart ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ usort-default   [96.31 ms]: ▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆ ┃
┃ usort-optimized [70.97 ms]: ▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆              ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ (lower is …
```

Skip visiting CST nodes that cannot have import statements

---

usort/sorting.py
usort/tests/functional.py

https://github.com/facebookexperimental/usort/pull/187 broke the logic that keeps track of indentation for the purposes of line length tracking by not letting `visit_IndentedBlock` run in the transformer.
This affected (import) lines that are long enough to fit `line_length` without the indentation, but too long if we count indentation too.
This PR adds a test case for this situation.

Make sure indentation is tracked

---

setup.cfg
usort/sorting.py
usort/tests/__init__.py
usort/tests/functional.py
usort/tests/sorting.py

Because we do block splitting before deduplication, it could previously try to pop the same name twice.
Fixes #194

Avoid KeyError when imports are duplicated.

---

docs/guide.rst
usort/sorting.py
usort/tests/functional.py
usort/translate.py

Since we can't easily reason about or handle lines with multiple
statements (separated by semicolons), this improves usort's behavior by
treating them as unsortable, effectively becoming barriers between
blocks of imports. This fixes an issue where assertions failed when
transforming nodes into dataclasses.
Fixes #203

Treat lines with multiple statements as barriers

---

.github/workflows/build.yml
Makefile
check_backcompat.py

Adds a simple script that parses the PyPI JSON API for public (non-yanked) releases
of `usort >= 1.0`, and then checks those old versions against sorting from the
current/local version, and passes only if all of those previous versions produce
no changes.
Example output:
```
$ make backcompat
python check_backcompat.py
discovered versions 1.0.4, 1.0.2, 1.0.1, 1.0.0
sorting with local version ...
usort, version 1.0.3.dev47+g6cc5725.d20220913
done
checking version 1.0.4 ...
usort, version 1.0.4
clean
checking version 1.0.2 ...
usort, version 1.0.2
clean
checking version 1.0.1 ...
usort, version 1.0.1
clean
checking version 1.0.0 ...
usort, version 1.0.0
clean
success!
```

Script and CI action to validate backwards compatibility

---

usort/cli.py
usort/sorting.py
usort/tests/functional.py
usort/tests/sorting.py

The simplest possible method of handling #163:
Removes all blank lines between imports within a single category. No exceptions.

Uniformly collapse blank lines within a category

---

.github/workflows/build.yml

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #236

Remove check-deps actions

---

docs/api.rst
usort/cli.py
usort/tests/__main__.py
usort/tests/cli.py
usort/tests/util.py
usort/util.py

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #244
Adds a helper function to detect the presence of the `libcst.native`
parser module, and enable its use in LibCST appropriately. If the native
module is not available, or it does not contain the `parse_module`
function that we expect to use, then the native parser is not enabled.
Adds support for parsing 3.10 match statements, as well as future syntax
that requires use of the PEG parsing features only available in LibCST's
native parser.
This is currently only enabled in the µsort CLI entrypoint. Programs
using the µsort API directly will need to call or enable the native
parser separately if desired.
Fixes #216

Detect/enable the native LibCST parser by default

---

usort/tests/functional.py
usort/translate.py

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #252
* __->__ #251
* #250
Fixes #249

Correctly track inline comments on items without trailing commas

---

usort/stdlibs.py
usort/tests/stdlibs.py

Addresses https://github.com/omnilib/stdlibs/issues/57#issuecomment-1643112650.

remove py27 only modules from known stdlib
